# Generated by Django 3.1.2 on 2020-10-26 16:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Precio unidad')),
                ('decription', ckeditor.fields.RichTextField(verbose_name='Descripcion del Producto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Cursos', verbose_name='Imagen Curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
