# Generated by Django 5.0.7 on 2024-07-12 05:27

import django.contrib.postgres.fields
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_blog', models.CharField(choices=[('P', 'Proyecto'), ('I', 'Proyecto INDI'), ('E', 'Blog')], max_length=1, verbose_name='Tipo blog')),
                ('title', models.CharField(max_length=120, verbose_name='titulo')),
                ('resume', models.CharField(max_length=150, verbose_name='Resumen Blog')),
                ('content', django_quill.fields.QuillField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog-portfolio', verbose_name='Imagen Blog')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('publicado', models.BooleanField(default=False)),
                ('video', models.URLField(blank=True)),
                ('date', models.DateField(verbose_name='Fecha Publicacion')),
                ('visits', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Blog Portfolio',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='titulo')),
                ('subtitle', models.CharField(max_length=150, verbose_name='subtitulo')),
                ('description', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('link_blog', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Skills portfolio',
                'verbose_name_plural': 'Skills portfolio',
            },
        ),
        migrations.CreateModel(
            name='HomePortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='titulo')),
                ('subtitle', models.CharField(max_length=120, verbose_name='sub titulo')),
                ('description', models.CharField(max_length=200, verbose_name='descripcion')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo-portfolio', verbose_name='Foto')),
                ('content', django_quill.fields.QuillField()),
                ('text_footer', models.CharField(max_length=200, verbose_name='Mensaje Footer')),
                ('visits', models.IntegerField(default=0)),
                ('contry', models.CharField(max_length=50, verbose_name='pais')),
                ('linkeding', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('title_seo', models.CharField(max_length=200, verbose_name='Titulo SEO')),
                ('description_seo', models.CharField(max_length=200, verbose_name='Descripcion SEO')),
                ('kwords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
            ],
            options={
                'verbose_name': 'Home Portafolio',
                'verbose_name_plural': 'Home Pages',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='titulo')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='skills-portfolio', verbose_name='logo')),
                ('nivel', models.CharField(max_length=25, verbose_name='Nivel')),
                ('link', models.URLField(blank=True)),
                ('link_certificate', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Skills portfolio',
                'verbose_name_plural': 'Skills portfolio',
            },
        ),
    ]
