# Generated by Django 3.1.2 on 2022-09-12 22:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('visits', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('num_videos', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sheriffMapa', verbose_name='Imagen')),
                ('color', models.CharField(blank=True, max_length=10, verbose_name='color')),
                ('contenido', ckeditor.fields.RichTextField(verbose_name='Descripcion Mapa')),
                ('public', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
            },
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sheriffLogo', verbose_name='Imagen logo')),
                ('video', models.URLField(blank=True)),
                ('video_id', models.CharField(max_length=10, verbose_name='video id')),
                ('tiempo', models.CharField(max_length=5, verbose_name='tiempo')),
            ],
            options={
                'verbose_name': 'Clip',
                'verbose_name_plural': 'Clip',
            },
        ),
        migrations.CreateModel(
            name='HomeSheriff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('username', models.CharField(max_length=30, verbose_name='username')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='sheriffLogo', verbose_name='Imagen logo')),
                ('link_main', models.URLField(blank=True)),
                ('link_uno', models.URLField(blank=True)),
                ('link_dos', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home Sheriff',
            },
        ),
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('visits', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sheriffMapa', verbose_name='Imagen')),
                ('color', models.CharField(blank=True, max_length=10, verbose_name='color')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripcion Mapa')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home Sheriff',
            },
        ),
    ]
