# Generated by Django 3.1.2 on 2022-09-13 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheriff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapa',
            options={'verbose_name': 'Mapa', 'verbose_name_plural': 'Mapas'},
        ),
        migrations.AddField(
            model_name='clip',
            name='agente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sheriff.agente', verbose_name='agente_clip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clip',
            name='mapa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sheriff.mapa', verbose_name='mapa_clip'),
            preserve_default=False,
        ),
    ]
