# Generated by Django 3.1.2 on 2022-09-13 06:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheriff', '0002_auto_20220912_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripcion Mapa'),
        ),
    ]
